[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

[phases.setup]
nixPkgs = [
  "nodejs_22",
  "chromium",
  "ffmpeg"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"