export const BACKEND_URL = "";

export const TEXT = {
  id: {
    title: "VS Tools PRO",
    subtitle:
      "Editor video slideshow profesional dengan audio sync, subtitle AI/manual, waveform, template marketplace, cloud save, dan backend render panjang.",
    uploadImages: "Upload Gambar",
    uploadAudio: "Tambah Audio",
    saveProject: "Save Project",
    loadProject: "Load Project",
    saveCloud: "Save Cloud",
    loadCloud: "Load Cloud",
    exportBackend: "Backend Render Panjang",
    play: "Play",
    pause: "Pause",
    videoSize: "Ukuran Video",
    slideEditor: "Editor Slide",
    subtitleEditor: "Subtitle",
    addSubtitle: "Tambah Subtitle",
    autoSubtitle: "Auto Subtitle AI",
    removeBg: "Remove Background AI",
    removeObject: "Remove Object AI",
    autoFit: "Auto Fit Slides to Audio",
    start: "Start",
    end: "End",
    zoom: "Zoom",
    background: "Visual Background",
    transition: "Transisi",
    animation: "Animasi",
    imageMode: "Mode Gambar",
    templateMarketplace: "Template Marketplace",
    waveform: "Advanced Waveform"
  },

  en: {
    title: "VS Tools PRO",
    subtitle:
      "Professional slideshow video editor with audio sync, AI/manual subtitles, waveform, template marketplace, cloud save, and long backend rendering.",
    uploadImages: "Upload Images",
    uploadAudio: "Add Audio",
    saveProject: "Save Project",
    loadProject: "Load Project",
    saveCloud: "Save Cloud",
    loadCloud: "Load Cloud",
    exportBackend: "Long Backend Render",
    play: "Play",
    pause: "Pause",
    videoSize: "Video Size",
    slideEditor: "Slide Editor",
    subtitleEditor: "Subtitle",
    addSubtitle: "Add Subtitle",
    autoSubtitle: "Auto Subtitle AI",
    removeBg: "Remove Background AI",
    removeObject: "Remove Object AI",
    autoFit: "Auto Fit Slides to Audio",
    start: "Start",
    end: "End",
    zoom: "Zoom",
    background: "Visual Background",
    transition: "Transition",
    animation: "Animation",
    imageMode: "Image Mode",
    templateMarketplace: "Template Marketplace",
    waveform: "Advanced Waveform"
  },

  zh: {
    title: "VS Tools PRO",
    subtitle:
      "专业幻灯片视频编辑器，支持音频同步、AI/手动字幕、波形、模板市场、云保存和长视频后端渲染。",
    uploadImages: "上传图片",
    uploadAudio: "添加音频",
    saveProject: "保存项目",
    loadProject: "加载项目",
    saveCloud: "云保存",
    loadCloud: "云加载",
    exportBackend: "长视频后端渲染",
    play: "播放",
    pause: "暂停",
    videoSize: "视频尺寸",
    slideEditor: "幻灯片编辑器",
    subtitleEditor: "字幕",
    addSubtitle: "添加字幕",
    autoSubtitle: "AI 自动字幕",
    removeBg: "AI 移除背景",
    removeObject: "AI 移除物体",
    autoFit: "自动适配音频",
    start: "开始",
    end: "结束",
    zoom: "缩放",
    background: "视觉背景",
    transition: "转场",
    animation: "动画",
    imageMode: "图片模式",
    templateMarketplace: "模板市场",
    waveform: "高级波形"
  }
};

export const VIDEO_SIZES = {
  landscape: {
    label: "Landscape 16:9 — YouTube 1280x720",
    width: 1280,
    height: 720
  },
  portrait: {
    label: "Portrait 9:16 — TikTok/Reels 720x1280",
    width: 720,
    height: 1280
  },
  square: {
    label: "Square 1:1 — Instagram 720x720",
    width: 720,
    height: 720
  },
  vertical: {
    label: "Vertical 4:5 — Social Feed 720x900",
    width: 720,
    height: 900
  },
  fullhd: {
    label: "Full HD — 1920x1080",
    width: 1920,
    height: 1080
  },
  cinematic: {
    label: "Cinematic 21:9 — 1920x820",
    width: 1920,
    height: 820
  }
};

export const BACKGROUNDS = [
  "pinkSilver",
  "modern",
  "traditional",
  "nature",
  "mountain",
  "ocean",
  "forest",
  "sunset",
  "technology",
  "aiNeon",
  "blockchain",
  "cryptoNetwork",
  "cyberGrid",
  "minimalApple",
  "luxuryDark",
  "goldLuxury",
  "cleanWhite",
  "deepSpace",
  "cyberPink",
  "matrixGreen",
  "documentary",
  "classicPaper",
  "tropical",
  "desert",
  "cityNight",
  "aurora",
  "galaxy",
  "neonGlass",
  "royalPurple",
  "businessDark",
  "startupBlue",
  "cryptoGold",
  "ecoGreen",
  "softPastel",
  "filmNoir",
  "retroVHS",
  "animeSky",
  "abstractLiquid",
  "gridFuture"
];

export const BACKGROUND_LABELS = {
  pinkSilver: "Pink Silver",
  modern: "Modern Dark",
  traditional: "Traditional Classic",
  nature: "Nature Green",
  mountain: "Mountain",
  ocean: "Ocean",
  forest: "Forest",
  sunset: "Sunset",
  technology: "Technology",
  aiNeon: "AI Neon",
  blockchain: "Blockchain",
  cryptoNetwork: "Crypto Network",
  cyberGrid: "Cyber Grid",
  minimalApple: "Minimal Apple",
  luxuryDark: "Luxury Dark",
  goldLuxury: "Gold Luxury",
  cleanWhite: "Clean White",
  deepSpace: "Deep Space",
  cyberPink: "Cyber Pink",
  matrixGreen: "Matrix Green",
  documentary: "Documentary",
  classicPaper: "Classic Paper",
  tropical: "Tropical",
  desert: "Desert",
  cityNight: "City Night",
  aurora: "Aurora",
  galaxy: "Galaxy",
  neonGlass: "Neon Glass",
  royalPurple: "Royal Purple",
  businessDark: "Business Dark",
  startupBlue: "Startup Blue",
  cryptoGold: "Crypto Gold",
  ecoGreen: "Eco Green",
  softPastel: "Soft Pastel",
  filmNoir: "Film Noir",
  retroVHS: "Retro VHS",
  animeSky: "Anime Sky",
  abstractLiquid: "Abstract Liquid",
  gridFuture: "Grid Future"
};

export const TRANSITIONS = [
  "fade",
  "zoom",
  "slideLeft",
  "slideRight",
  "slideUp",
  "slideDown",
  "rise",
  "rotateIn",
  "blurReveal",
  "glitch",
  "filmBurn",
  "flashCut",
  "glassFade",
  "cinematicFade",
  "softFlash",
  "wipeLeft",
  "wipeRight",
  "wipeUp",
  "wipeDown",
  "pushLeft",
  "pushRight",
  "spinZoom",
  "dreamBlur",
  "matrixGlitch",
  "neonSwipe",
  "paperSlide",
  "classicDissolve",
  "cameraFlash",
  "vhsNoise",
  "luxuryReveal"
];

export const TRANSITION_LABELS = {
  fade: "Fade",
  zoom: "Cinematic Zoom",
  slideLeft: "Slide Left",
  slideRight: "Slide Right",
  slideUp: "Slide Up",
  slideDown: "Slide Down",
  rise: "Rise Up",
  rotateIn: "Rotate In",
  blurReveal: "Blur Reveal",
  glitch: "Glitch",
  filmBurn: "Film Burn",
  flashCut: "Flash Cut",
  glassFade: "Glass Fade",
  cinematicFade: "Cinematic Fade",
  softFlash: "Soft Flash",
  wipeLeft: "Wipe Left",
  wipeRight: "Wipe Right",
  wipeUp: "Wipe Up",
  wipeDown: "Wipe Down",
  pushLeft: "Push Left",
  pushRight: "Push Right",
  spinZoom: "Spin Zoom",
  dreamBlur: "Dream Blur",
  matrixGlitch: "Matrix Glitch",
  neonSwipe: "Neon Swipe",
  paperSlide: "Paper Slide",
  classicDissolve: "Classic Dissolve",
  cameraFlash: "Camera Flash",
  vhsNoise: "VHS Noise",
  luxuryReveal: "Luxury Reveal"
};

export const ANIMATIONS = [
  "none",
  "zoomIn",
  "zoomOut",
  "panLeft",
  "panRight",
  "panUp",
  "panDown",
  "slowDrift",
  "rotateSlow",
  "pulse",
  "floating",
  "cinematicPush",
  "documentaryMove",
  "parallaxLeft",
  "parallaxRight",
  "kenBurns",
  "microShake",
  "softBreath",
  "orbit",
  "tiltLeft",
  "tiltRight",
  "luxuryFloat",
  "techScan",
  "blockchainPulse",
  "natureSway",
  "paperFloat",
  "vhsJitter",
  "dramaticPull",
  "heroZoom",
  "smoothSlide"
];

export const ANIMATION_LABELS = {
  none: "None",
  zoomIn: "Zoom In",
  zoomOut: "Zoom Out",
  panLeft: "Pan Left",
  panRight: "Pan Right",
  panUp: "Pan Up",
  panDown: "Pan Down",
  slowDrift: "Slow Drift",
  rotateSlow: "Rotate Slow",
  pulse: "Pulse",
  floating: "Floating",
  cinematicPush: "Cinematic Push",
  documentaryMove: "Documentary Move",
  parallaxLeft: "Parallax Left",
  parallaxRight: "Parallax Right",
  kenBurns: "Ken Burns",
  microShake: "Micro Shake",
  softBreath: "Soft Breath",
  orbit: "Orbit",
  tiltLeft: "Tilt Left",
  tiltRight: "Tilt Right",
  luxuryFloat: "Luxury Float",
  techScan: "Tech Scan",
  blockchainPulse: "Blockchain Pulse",
  natureSway: "Nature Sway",
  paperFloat: "Paper Float",
  vhsJitter: "VHS Jitter",
  dramaticPull: "Dramatic Pull",
  heroZoom: "Hero Zoom",
  smoothSlide: "Smooth Slide"
};

export const TEMPLATE_PRESETS = [
  {
    id: "modern-ai",
    title: "Modern AI",
    category: "technology",
    background: "aiNeon",
    transition: "neonSwipe",
    animation: "techScan",
    description: "Clean AI startup style with neon movement."
  },
  {
    id: "blockchain-pro",
    title: "Blockchain Pro",
    category: "crypto",
    background: "blockchain",
    transition: "matrixGlitch",
    animation: "blockchainPulse",
    description: "Crypto/network visual language for Web3 decks."
  },
  {
    id: "nature-calm",
    title: "Nature Calm",
    category: "nature",
    background: "nature",
    transition: "classicDissolve",
    animation: "natureSway",
    description: "Soft natural motion for calm storytelling."
  },
  {
    id: "classic-paper",
    title: "Classic Paper",
    category: "traditional",
    background: "classicPaper",
    transition: "paperSlide",
    animation: "paperFloat",
    description: "Traditional presentation style with warm tones."
  },
  {
    id: "luxury-brand",
    title: "Luxury Brand",
    category: "brand",
    background: "goldLuxury",
    transition: "luxuryReveal",
    animation: "luxuryFloat",
    description: "Premium brand video look with gold-dark style."
  },
  {
    id: "apple-minimal",
    title: "Apple Minimal",
    category: "minimal",
    background: "minimalApple",
    transition: "glassFade",
    animation: "softBreath",
    description: "Minimal white/silver presentation style."
  },
  {
    id: "cinematic-doc",
    title: "Cinematic Documentary",
    category: "documentary",
    background: "documentary",
    transition: "cinematicFade",
    animation: "documentaryMove",
    description: "Documentary style movement and smooth pacing."
  },
  {
    id: "vhs-retro",
    title: "Retro VHS",
    category: "retro",
    background: "retroVHS",
    transition: "vhsNoise",
    animation: "vhsJitter",
    description: "Retro social content style."
  }
];